name: deploy

on:
  workflow_dispatch:
  
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/cache@v3
        with:
          path: |
            .terraform/**
            .terraform.lock.hcl
            plan.cache
          key: terraform-lock-${{ github.event.workflow_run.head_branch }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Plan
        id: plan
        run: |
          terraform init
          terraform plan -no-color -out plan_cache.json 
      - name: Terraform apply
        run: terraform apply -input=false -no-color -auto-approve plan_cache.json
      - name: Kubeconf artefact
        uses: actions/upload-artifact@v2
        with:
          name: kubeconf
          path: |
            kube/*
          retention-days: 1
  Rds_Catalogo:
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}
          
      - name: GET Endpoint RDS
        run: |
          ENDPOINT=`aws rds describe-db-instances --db-instance-identifier teste --query 'DBInstances[0].Endpoint.Address'`
          echo $ENDPOINT
          echo "endpoint=$ENDPOINT" >> $GITHUB_ENV

      - name: Write Catalogo Info
        run: |
          yq e '.metadata.environment.endpoint = ${{ env.endpoint }}' -i catalog-info.yaml
          cat ./catalog-info.yaml
  
      - name: Publish Catalogo Info
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          DESTINATION_BRANCH: master
        with:
          destination_branch: master
          source_file: './catalog-info.yaml'
          destination_repo: ${{ github.repository }}
          destination_folder: '/'
          commit_message: Update catalog-info.yaml in the same repo
          git_server: github.com
